HebrewEvents =
  EighthDayOfPesach: "אַחֲרוֹן שֶׁל פֶּסַח"
  ErubTabshilin: "עֵרוּב תַּבְשִׁלִין"
  FastOfGedaliah: "צוֹם גְּדַלְיָה"
  FirstDayOfSheminiAseret: "שְּׁמִינִי עֲצֶרֶת"
  FirstYomTobOfPesach: "פֶּסַח"
  FirstYomTobOfSukkot: "סֻּכּוֹת"
  Hanuka: "חֲנֻכַּה"
  LagLaomer: "ל``ג לָעֹמֶר"
  MaharHodesh: "מָחָר חֹדֶשׁ"
  Moed: "חוֹל הַמוֹעֵד"
  NinthOfAb: "תִּשְׁעָה בְּאָב"
  PesachSheni: "פֶּסַח שֵׁנִי"
  Purim: "פּוּרִים"
  PurimKatan: "פּוּרִים קָטָן"
  FirstDayOfRoshHashana: "רֹאשׁ הַשָּׁנָה"
  SecondDayOfRoshHashana: "רֹאשׁ הַשָּׁנָה"
  RoshHodesh: "רֹאשׁ חֹדֶשׁ"
  SeventeenthOfTamuz: "שִׁבְעָה עֲשָׂר בְּתַּמוּז"
  SeventhDayOfPesach: "שְׁבִיעִי שֶׁל פֶּסַח"
  ShabbatHaGadol: "שַׁבָּת הַגָּדוֹל"
  ShabbatHaHodesh: "שַׁבָּת הַחֹדֶשׁ"
  ShabbatHazon: "שַׁבָּת חֲזוֹן"
  ShabbatNahamu: "שַׁבָּת נַחֲמוּ"
  ShabbatSheqalim: "שַׁבָּת שְׁקָלִים"
  ShabbatShuba: "שַׁבָּת שׁוּבָה"
  ShabbatParah: "שַׁבָּת פָּרָה"
  ShabbatZachor: "שַׁבָּת זָכוֹר"
  Shabuot: "חַג הַשָׁבֻעֹת"
  ShushanPurim: "שׁוּשַׁן פּוּרִים"
  ShushanPurimKatan: "שׁוּשַׁן פּוּרִים קָטָן"
  SimhatTorah: "שִׂמְחַת תּוֹרָה"
  TaanitEster: "תַּעֲנִית אֶסְתֵּר"
  TenthOfTebet: "עֲשָׂרָה בְּטֵבֵת"
  TuBAb: "ט``ו בְּאָב"
  TuBiShvat: "ט``ו בִּשְׁבָט"
  YomKippur: "יוֹם הַכִּפֻּרִים"

DetailedHebrewEvents =
  ErebRoshHashana: "Fast until מִנְחָה"
  ErebShabuot: "תִּקוּן לֵיל שָׁבֻעֹת<br>&nbsp;&nbsp;&nbsp;&nbsp;<small class='no-wrap'>(Bring lense solution and a towel)</small>"
  FirstDayOfPesach: "תִּקוּן הַטַּל<br>Tonight: קְצִירַת הָעֹמֶר"
  SixthDayOfPesach: "<small>Tonight: תִּקוּן לֵיל<br>&nbsp;&nbsp;&nbsp;&nbsp;שְׁבִיעִי שֶׁל פֶּסַח</small>"
  SixthDayOfSukkot: "Tonight: תִּקוּן לֵיל<br>&nbsp;&nbsp;&nbsp;&nbsp;הוֹשַׁעֲנָא רַבָּא"

(exports ? this).HebrewEvents = HebrewEvents
(exports ? this).DetailedHebrewEvents = DetailedHebrewEvents
