HebrewEvents =
  BedikatHames: "Tonight: בְּדִיקַת חָמֵץ"
  BeginTalUmatar: "Begin טַל וּמָטָר<br>&nbsp;&nbsp;&nbsp;&nbsp;at עַרְבִית"
  BirkatHaIlanot: "בִּרְכַּת הָאִילָנוֹת (two trees)"
  BiurHames: "בִּעוּר חָמֵץ"
  EighthDayOfPesach: "<small>אַחֲרוֹן שֶׁל פֶּסַח</small>"
  ErebKippur: "כַּפָּרוֹת"
  ErebPurim: "קְרִיאַת הַמְגִּילִָה"
  ErebShabuot: "תִּקוּן לֵיל שָׁבֻעֹת"
  ErubTabshilin: "עֵרוּב תַּבְשִׁלִין"
  FastOfGedaliah: "צוֹם גְּדַלְיָה"
  FirstDayOfPesach: "תִּקוּן הַטַּל"
  FirstDayOfSheminiAseret: "שְּׁמִינִי עֲצֶרֶת<br>תִּקוּן גֶשֶׁם"
  FirstYomTobOfPesach: "יוֹם טוֹב רִאשׁוֹן שֶׁל פֶּסַח"
  FirstYomTobOfSukkot: "יוֹם טוֹב רִאשׁוֹן שֶׁל סֻּכּוֹת"
  Hanuka: "חֲנֻכַּה"
  HataratNedarim: "הָתַּרָת נְדָרים"
  KalHamira: "כָּל חֲמִירָא"
  LagLaomer: "ל``ג לָעֹמֶר"
  MaharHodesh: "מָחָר חֹדֶשׁ"
  Moed: "חוֹל הַמוֹעֵד"
  Nesiim: "נְשִׂאִים"
  NinthOfAb: "תִּשְׁעָה בְּאָב"
  PesachSheni: "פֶּסַח שֵׁנִי"
  Purim: "פּוּרִים<br>קְרִיאַת הַמְגִּילִָה<br>מִשְׁלֹחַ מָנוֹת<br>מַתָּנוֹת לָאֶבְיֹנִים<br>סְעוּדַת מִשְׁתֶּה"
  PurimKatan: "פּוּרִים קָטָן"
  FirstDayOfRoshHashana: "רֹאשׁ הַשָּׁנָה<br>תַּשְׁלְיךְ"
  SecondDayOfRoshHashana: "רֹאשׁ הַשָּׁנָה"
  RoshHodesh: "רֹאשׁ חֹדֶשׁ"
  SeventeenthOfTamuz: "שִׁבְעָה עֲשָׂר בְּתַּמוּז"
  SeventhDayOfPesach: "שְׁבִיעִי שֶׁל פֶּסַח"
  ShabbatHaGadol: "שַׁבָּת הַגָּדוֹל"
  ShabbatHaHodesh: "שַׁבָּת הַחֹדֶשׁ"
  ShabbatHazon: "שַׁבָּת חֲזוֹן"
  ShabbatNahamu: "שַׁבָּת נַחֲמוּ"
  ShabbatSheqalim: "שַׁבָּת שְׁקָלִים"
  ShabbatShuba: "שַׁבָּת שׁוּבָה"
  ShabbatParah: "שַׁבָּת פָּרָה"
  ShabbatZachor: "שַׁבָּת זָכוֹר"
  Shabuot: "חַג הַשָׁבֻעֹת<br>אַזְהָרוֹת<br>מְגִּילַת רוּת"
  ShushanPurim: "שׁוּשַׁן פּוּרִים"
  ShushanPurimKatan: "שׁוּשַׁן פּוּרִים קָטָן"
  SimhatTorah: "שִׂמְחַת תּוֹרָה"
  TaanitEster: "תַּעֲנִית אֶסְתֵּר<br>זֵכֶר לְמַחֲצִית הַשֶּׁקֶל"
  TefillatHaParnasa: "תְּפִלָּת הָפַּרְנָסָה"
  TefilatHaShelah: "תְּפִלָּת הָשְׁלָ``ה"
  TenthOfTebet: "עֲשָׂרָה בְּטֵבֵת"
  TuBAb: "ט``ו בְּאָב"
  TuBiShvat: "ט``ו בִּשְׁבָט"
  Ushpizin: "Tonight: אוּשְׁפִּיזִּין"
  YomKippur: "יוֹם הַכִּפֻּרִים"

DetailedHebrewEvents =
  ErebRoshHashana: "Fast until מִנְחָה"
  ErebShabuot: "תִּקוּן לֵיל שָׁבֻעֹת<br>&nbsp;&nbsp;&nbsp;&nbsp;<small class='no-wrap'>(Bring lense solution and a towel)</small>"
  FirstDayOfPesach: "תִּקוּן הַטַּל<br>Tonight: קְצִירַת הָעֹמֶר"
  SixthDayOfPesach: "<small>Tonight: תִּקוּן לֵיל<br>&nbsp;&nbsp;&nbsp;&nbsp;שְׁבִיעִי שֶׁל פֶּסַח</small>"
  SixthDayOfSukkot: "Tonight: תִּקוּן לֵיל<br>&nbsp;&nbsp;&nbsp;&nbsp;הוֹשַׁעֲנָא רַבָּא"

(exports ? this).HebrewEvents = HebrewEvents
(exports ? this).DetailedHebrewEvents = DetailedHebrewEvents
